# menu
menu:
    Blog: /
    Archive: /archives/
    Tag: /tags
    Link: /links
# header image
headerimg: https://cdn.weic96.cn/website/a/15/4545620ec1ce9ee9147a91ab69c06.jpg
# logo
logo: images/logo.jpg
# config favicon
favicon: images/favicon.png
# scoial username
github: liaobinbin
weibo: mycxs
mail: doubiliao@gmail.com
rss: /atom.xml
# copyright year
year: 2017

version: 1.0.0